const CONFIG = {
    introTitle: 'He luu cậu!!',
    introDesc: 'tớ có điều này muốn hỏi cậu nhớ phải trả lời thật lòng nhaaaa',
    btnIntro: 'Ok',
    title: 'Cậu yêu tớ có phải không nào',
    desc: 'nếu cậu không trả lời mà thoát ra tức là muốn làm vợ tớ rồi đó nha :v ',
    btnYes: 'Yêu ơi là yêuuu <3333',
    btnNo: 'Cậu mơ à :3333',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h anh qua đón nhé công chúa.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://m.me/QING1750'
